### ISSUE TITLE
InvalidParameterException

### ISSUE THREAD

**Issue by haydenth** [kislyuk/watchtower#11]
Hello - I'm running this in a production environment and every few hours, watchtower will stop recording to cloudwatch and dump the following exception into my logs.  Any idea what it could be?

```
[Mon Nov 16 19:33:53.036691 2015] [:error] [pid 11413] Exception in thread Thread-2:
[Mon Nov 16 19:33:53.036752 2015] [:error] [pid 11413] Traceback (most recent call last):
[Mon Nov 16 19:33:53.036762 2015] [:error] [pid 11413]   File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
[Mon Nov 16 19:33:53.036771 2015] [:error] [pid 11413]     self.run()
[Mon Nov 16 19:33:53.036779 2015] [:error] [pid 11413]   File "/usr/lib64/python2.7/threading.py", line 766, in run
[Mon Nov 16 19:33:53.036788 2015] [:error] [pid 11413]     self.__target(*self.__args, **self.__kwargs)
[Mon Nov 16 19:33:53.036796 2015] [:error] [pid 11413]   File "/opt/python/run/venv/lib/python2.7/site-packages/watchtower/__init__.py", line 140, in batch_sender
[Mon Nov 16 19:33:53.036805 2015] [:error] [pid 11413]     self._submit_batch(cur_batch, stream_name)
[Mon Nov 16 19:33:53.036813 2015] [:error] [pid 11413]   File "/opt/python/run/venv/lib/python2.7/site-packages/watchtower/__init__.py", line 76, in _submit_batch
[Mon Nov 16 19:33:53.036822 2015] [:error] [pid 11413]     response = self.cwl_client.put_log_events(**kwargs)
[Mon Nov 16 19:33:53.036830 2015] [:error] [pid 11413]   File "/opt/python/run/venv/lib/python2.7/site-packages/botocore/client.py", line 310, in _api_call
[Mon Nov 16 19:33:53.036839 2015] [:error] [pid 11413]     return self._make_api_call(operation_name, kwargs)
[Mon Nov 16 19:33:53.036847 2015] [:error] [pid 11413]   File "/opt/python/run/venv/lib/python2.7/site-packages/botocore/client.py", line 395, in _make_api_call
[Mon Nov 16 19:33:53.036855 2015] [:error] [pid 11413]     raise ClientError(parsed_response, operation_name)
[Mon Nov 16 19:33:53.036864 2015] [:error] [pid 11413] ClientError: An error occurred (InvalidParameterException) when calling the PutLogEvents operation: Log events in a single PutLogEvents request must be in chronological order.
```

**Comment by haydenth** [comment]
I see the error appears to be coming from here: https://github.com/kislyuk/watchtower/blob/master/watchtower/__init__.py#L76

According to boto: The log events in the batch must be in chronological ordered by their timestamp, called from line 140. Would it be unreasonable to send a pull request adding a sort?

**Comment by kislyuk** [comment]
Sounds great, thank you for finding this. I will accept a PR.
