### ISSUE TITLE
Running python manage.py migrate if the root log level is DEBUG hangs in watchtower __init__.py

### ISSUE THREAD

**Issue by andrek-data-axle** [kislyuk/watchtower#115]
Running python manage.py migrate if the root log level is DEBUG hangs in watchtower.
If I hit Ctrl-C I get the following
^CError in atexit._run_exitfuncs:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/logging/__init__.py", line 2036, in shutdown
    h.flush()
  File "/var/app/venv/staging-LQM1lest/lib/python3.7/site-packages/watchtower/__init__.py", line 254, in flush
    q.join()
  File "/usr/lib64/python3.7/queue.py", line 89, in join
    self.all_tasks_done.wait()
  File "/usr/lib64/python3.7/threading.py", line 296, in wait
    waiter.acquire()

Appears similar to     
https://github.com/kislyuk/watchtower/issues/93
https://github.com/kislyuk/watchtower/issues/65
Setting root log level to INFO fixes it...

**Comment by kislyuk** [comment]
Yes, this behavior is expected. Because the botocore library emits log messages when making network requests, you can't safely shut down the logger without triggering an infinite loop. To avoid this issue, set the log level for botocore and urllib3 to INFO or above. I have also released a workaround that should act as a failsafe in this case. See the discussion in #93.
