### ISSUE TITLE
NameError: name 'Mapping' is not defined, when using a custom boto3 session

### ISSUE THREAD

**Issue by neilpanchal** [kislyuk/watchtower#142]
When using a custom boto3 session during handler initialization as follows, I am getting an error that Mapping is not defined in `watchtower.__init__.py`. 

```python
# Botocore
boto_session = boto3.session.Session(
    aws_access_key_id=app.config['AWS_ACCESS_KEY_ID'],
    aws_secret_access_key=app.config['AWS_SECRET_ACCESS_KEY'],
    region_name=app.config['AWS_REGION']
)

# Logging
logging.basicConfig(level=logging.INFO)
handler = watchtower.CloudWatchLogHandler(boto3_session=boto_session) # <---- I want to use my own boto3 session.
app.logger.addHandler(handler)
logging.getLogger('werkzeug').addHandler(handler)
```

Error stack trace:

```
127.0.0.1 - - [14/Mar/2021 18:53:44] "GET /checkout HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/Volumes/macData/Dev/myproject/myproject-site/.venv/lib/python3.9/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/Volumes/macData/Dev/myproject/myproject-site/.venv/lib/python3.9/site-packages/werkzeug/serving.py", line 315, in execute
    write(data)
  File "/Volumes/macData/Dev/myproject/myproject-site/.venv/lib/python3.9/site-packages/werkzeug/serving.py", line 273, in write
    self.send_response(code, msg)
  File "/Volumes/macData/Dev/myproject/myproject-site/.venv/lib/python3.9/site-packages/werkzeug/serving.py", line 383, in send_response
    self.log_request(code)
  File "/Volumes/macData/Dev/myproject/myproject-site/.venv/lib/python3.9/site-packages/werkzeug/serving.py", line 434, in log_request
    self.log("info", '"%s" %s %s', msg, code, size)
  File "/Volumes/macData/Dev/myproject/myproject-site/.venv/lib/python3.9/site-packages/werkzeug/serving.py", line 443, in log
    _log(
  File "/Volumes/macData/Dev/myproject/myproject-site/.venv/lib/python3.9/site-packages/werkzeug/_internal.py", line 113, in _log
    getattr(_logger, type)(message.rstrip(), *args, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1442, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 948, in handle
    self.emit(record)
  File "/Volumes/macData/Dev/myproject/myproject-site/.venv/lib/python3.9/site-packages/watchtower/__init__.py", line 222, in emit
    if isinstance(message.msg, Mapping):
NameError: name 'Mapping' is not defined
```

To fix this, if I add `from collections import Mapping` atop `watchtower.__init__.py`, everything works as it should.

I hope I am not doing something that's not intended. Basically, I prefer to explicitly create a boto3 session than to rely on any other magic method behind the scenes and pass it to watchtower's handler.

Current clientside temporary fix:

```python
# Logging
logging.basicConfig(level=logging.INFO)
handler = watchtower.CloudWatchLogHandler(boto3_session=boto_session)
from collections import Mapping
watchtower.Mapping = Mapping
app.logger.addHandler(handler)
logging.getLogger('werkzeug').addHandler(handler)
```
Thanks!

**Comment by kislyuk** [comment]
Thanks for filing the bug - can you give the version of watchtower that exhibits this bug? The most recent release, and all releases I have checked, have the name `Mapping` imported correctly and I'm not sure how that error is possible in those versions.

**Comment by neilpanchal** [comment]
@kislyuk Sure, as follows:

```
♦ mysite-site / ➞  poetry show watchtower
name         : watchtower
version      : 1.0.6
description  : Python CloudWatch Logging

dependencies
 - boto3 >=1.9.253,<2
 ```
