### ISSUE TITLE
InvalidSequenceTokenException

### ISSUE THREAD

**Issue by JangoSteve** [kislyuk/watchtower#30]
Here's another issue that comes up occasionally. Every now and then, I'll see output such as the following in the stdout (or maybe stderr, I'm not separating the two) when logging to CloudWatch using Watchtower:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/watchtower/__init__.py", line 150, in batch_sender
    self._submit_batch(cur_batch, stream_name)
  File "/usr/local/lib/python2.7/site-packages/watchtower/__init__.py", line 91, in _submit_batch
    response = self.cwl_client.put_log_events(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 494, in _make_api_call
    raise ClientError(parsed_response, operation_name)
ClientError: An error occurred (InvalidSequenceTokenException) when calling the PutLogEvents operation: The given sequenceToken is invalid. The next expected sequenceToken is: [some long series of digits]
```

Sometimes (but not every time) after this happens during a running script, when the script finishes it won't exit. Not sure if it's is related or not.

**Comment by kislyuk** [comment]
Thanks for reporting. The handler is supposed to be able to recover from this error automatically, but it looks like there is a bug. I'll look into it ASAP.

**Comment by Audace** [comment]
@JangoSteve were you able to get around this? I'm getting this a ton now, which is in turn triggering a ThrottlingException error.

**Comment by JangoSteve** [comment]
No, our individual messages aren't mission critical yet, so have just been allowing it to keep happen until it's fixed.

**Comment by guemues** [comment]
It is giving one more exception when it tries to recover. This is not always but sometimes. It is also prohibit my docker container to exit.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/watchtower/__init__.py", line 92, in _submit_batch
    response = self.cwl_client.put_log_events(**kwargs)
  File "/usr/local/lib/python3.4/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.4/site-packages/botocore/client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSequenceTokenException) when calling the PutLogEvents operation: The given sequenceToken is invalid. The next expected sequenceToken is: YYY

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/threading.py", line 911, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.4/threading.py", line 859, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/site-packages/watchtower/__init__.py", line 156, in batch_sender
    self._submit_batch(cur_batch, stream_name)
  File "/usr/local/lib/python3.4/site-packages/watchtower/__init__.py", line 97, in _submit_batch
    response = self.cwl_client.put_log_events(**kwargs)
  File "/usr/local/lib/python3.4/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.4/site-packages/botocore/client.py", line 537, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidSequenceTokenException) when calling the PutLogEvents operation: The given sequenceToken is invalid. The next expected sequenceToken is: XXX
```

**Comment by sterwill** [comment]
You'll get an `InvalidSequenceTokenException` if there was a concurrent write to your log stream from another thread or process, anywhere in the world.  Sometimes you might get multiple `InvalidSequenceTokenException`s in a row, if there is a lot of concurrent writing going on.

In my system concurrent writes are prevented by using a unique log stream, but I still see `InvalidSequenceTokenException`s from Watchtower and I think it's due to a bug in `_submit_batch`.

If `_submit_batch` gets `InvalidSequenceTokenException`, it learns the latest sequence token and retries the batch, which succeeds.  However after the successfuly retry, `self.sequence_tokens[stream_name]` is never updated with the even newer sequence token from `response`, causing the next batch to fail with `InvalidSequenceTokenException` (and succeed after one retry), and so on.

I think the fix would be to assign the sequence token from `response` back to `self.sequence_tokens[stream_name]` before the `break` that ends the retry loop on a successful put.

**Comment by kislyuk** [comment]
Thanks @sterwill, the fix you propose was merged recently.

In general y
