### ISSUE TITLE
watchtower dies after connection error

### ISSUE THREAD

**Issue by bra-fsn** [kislyuk/watchtower#74]
Got this error:
```
/usr/local/lib/python2.7/dist-packages/watchtower/__init__.py:117: WatchtowerWarning: Failed to deliver logs: Could not connect to the endpoint URL: "https://logs.us-west-2.amazonaws.com/"
  warnings.warn("Failed to deliver logs: {}".format(e), WatchtowerWarning)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/watchtower/__init__.py", line 191, in batch_sender
    self._submit_batch(cur_batch, stream_name)
  File "/usr/local/lib/python2.7/dist-packages/watchtower/__init__.py", line 117, in _submit_batch
    warnings.warn("Failed to deliver logs: {}".format(e), WatchtowerWarning)
  File "/usr/lib/python2.7/warnings.py", line 33, in _show_warning
    file.write(formatwarning(message, category, filename, lineno, line))
  File "/usr/bin/docker-run.py", line 972, in write
    self.logger.log(level, msg.rstrip())
  File "/usr/lib/python2.7/logging/__init__.py", line 1238, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1293, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1303, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1343, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 766, in handle
    self.emit(record)
  File "/usr/local/lib/python2.7/dist-packages/watchtower/__init__.py", line 134, in emit
    logGroupName=self.log_group, logStreamName=stream_name)
  File "/usr/local/lib/python2.7/dist-packages/watchtower/__init__.py", line 19, in _idempotent_create
    _callable(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 648, in _make_api_call
    operation_model, request_dict, request_context)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 667, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 137, in _send_request
    success_response, exception):
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 231, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/usr/local/lib/python2.7/dist-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
EndpointConnectionError: Could not connect to the endpoint URL: "https://logs.us-west-2.amazonaws.com/"
```

And the parent script couldn't come out of this situation, further execution was blocked by watchtower.
Using:
```
watchtower==0.5.5
boto3==1.9.94
botocore==1.12.94
```

After some investigation I can add some context to this. The error is because I redirect stdout and stderr to a watchtower logger, similar to this:
```
class LogFile(object):
    def __init__(self, name=None, stdout=None, stdout_encoding=None, **kwargs):
        self.stdout = stdout
        self.stdout_encoding = stdout_encoding
        self.logger = logging.getLogger(name)
        # don't write to the stdout from the logger, we'll do this manually
        self.logger.propagate = False
        self.logger.addHandler(watchtower.CloudWatchLogHandler(**kwargs))

    def write(self, msg, level=logging.INFO):
        try:
            self.stdout.write(msg)
        except TypeError:
            self.stdout.write(msg.decode(self.stdout_encoding))
        # strip newlines on the right, we don't need them in Cloudwatch logs
        msg = msg.rstrip()
        # don't log an empty message
        if len(msg):
            self.logger.log(level, msg.rstrip())

    def flush(self):
        for handler in self.logger.handlers:
            handler.flush()

try:
    # py3k needs this for writing bytes
    stdout = sys.stdout.buffer
except AttributeError:
    stdout = sys.stdout
stdout_encoding = sys.stdout.encoding
# Redirect stdout and stderr
o_stdout = sys.stdout
o_stderr = sys.stderr
for s in ('stdout', 'stderr'):
    # retry due AWS failing
    for i in range(8):
        try:
            setattr(sys, s, LogFile(s, stdout, stdout_encoding,
                                    log_group=log_group, stream_name=log_stream,
                                    send_interval=2,
                                    boto3_session=session))
            break
        except Exception:
            print("Try #{}".format(i))
            traceback.print_exc()
        time.sleep(i**1.2)
    else:
        print("Couldn't initialize CloudWatch Logs for {}".format(s))
```

The problem arises when in botocore's BaseChecker _check_caught_exception raises an exception (like when CWL dying in the above stacktrace) at https://github.com/boto/botocore/blob/d451e07657c1e8f94d22591d247ccb8677338839/botocore/retryhandler.py#L222
Normally this shouldn't be a problem, but my case is special, because stdout is redirected to watchtower, this exception could be raised in watchtower's warnings calls, like it happened.
Because this is not catched, the whole thread dies and on flush/close the program join()s the queue, which has no handler thread and waits indefinitely.

I guess this could be solved at least in two ways:
1. ignore watchtower's warnings, like with this: warnings.filterwarnings('ignore', category=watchtower.WatchtowerWarning)
2. wrap all instances of warnings (or everything, which could print to stdout/stderr) into try/except clauses

Another workaround would be to wait only for a given amount of time at flush, so if anything dies, it won't hang there forever.

**Comment by kislyuk** [comment]
Thanks for your interest in watchtower. Redirecting your own application's stdout and stderr into a watchtower logger is not supported, since it will result in an infinite loop whenever an issue like this occurs. While watchtower filters out boto3/botocore log messages that result from its own operations, it does not have a way to check if it needs to filter arbitrary inputs to avoid infinite recursion.

Additionally, errors like the above are now handled cleanly in watchtower without blocking the parent process, by calling logging.Handler.handleError.
